### ISSUE TITLE
our ensime-company binding of TAB doesn't always do the right thing

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#217]
I'm finding that TAB conflicts between yasnippet and company-mode at the best of times, but our binding to use it to force a company mode completion is confusing me.

It seems that normal company mode does not offer the majority of our completions (e.g. method suggestions), so the user has to explicitly type TAB to prompt for the suggestions. This is not typical company-mode usage, afaik, but I can understand that it might be a performance hack for ensime --- TAB is usually about expanding to the common substring.

In any case, I hit the following when reporting a bug with company-mode / yasnippet interaction that I believe actually sits with ENSIME:

https://github.com/company-mode/company-mode/issues/390

Going on the assumption that we need users to press TAB to get ENSIME completion suggestions, it should not interfere with yasnippet expansions.

**Comment by aemoncannon** [comment]
FWIW, our company backend is pretty simple. We are using company's async support, but we don't do any special caching or optimization. We do have a couple TAB-related hacks:
1) we overload TAB to trigger completion, but only in contexts where there is a valid prefix. This is similar to what autocomplete-mode does with its 'trigger key'.
2) if the cursor is at the end of a fully completed candidate, and you mash TAB, we trigger the yasnippet expansion for that method. Otherwise company won't run the action because there's no completion to be done.

TAB is just too popular a key..

**Comment by fommil** [comment]
Aah OK, of course because it's not always 2 characters before we want company to kick in, I wonder if maybe we could add a few triggers like the dot symbol for method completion.

It's probably the latter tab behaviour causing trouble. I'll investigate this week maybe.
