### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#322]
```
ensime-sbt.el:149:1:Error: Symbol's function definition is void: ensime-sbt-module-prompt-clauses
```

@jacobono

**Comment by jacobono** [comment]
hmmm.  Didn't see that.  I'm a little confused because that function is defined

https://github.com/ensime/ensime-emacs/blob/master/ensime-sbt.el#L129

Maybe this is a macro thing from `ensime-sbt-read-char-prompt`?

**Comment by fommil** [comment]
possibly, maybe it needs to be passed as a symbol reference rather than the variable name?

**Comment by jacobono** [comment]
I can try that.  What did you do exactly to get that compilation error? I'm not seeing it locally.  I only get an `eager evaluation warning` when I run `byte-compile-file`.

**Comment by fommil** [comment]
it was just the standard melpa install that flagged it up

**Comment by fommil** [comment]
I get the same thing if I run

```
cask pkg-file ;
      cask install ;
      cask build ;
```

**Comment by jacobono** [comment]
I'm still not getting that error on my local machine.

This is what I get when I run `cask build`

> ensime-sbt.el:149:1:Error: Not connected. M-x ensime to connect

Which I think is still a problem anyway.  :/ This is what I came up
with to not evaluate that function in the macro, but rather wait until
it is expanded to evaluate.

```lisp
(defmacro ensime-sbt-read-char-prompt (prompt verbose &rest cs)
  (let ((clauses (make-symbol "clauses"))
    	(cases (make-symbol "cases")))
    `(let* ((,clauses (if ,cs ',cs (ensime-sbt-module-prompt-clauses)))
	        (,cases (-map (lambda (c) (cons (car c) (cddr c))) ,clauses)))
       (pcase (read-char-choice
	       (concat ,prompt
		       (concat (mapconcat 'cadr ,clauses ", ")
			       (and ,verbose ", or [C-g] to abort") " "))
	       (mapcar 'car ,clauses))
	 ,cases))))
```

The only problem is I'm stuck here.  Wondering if you might be able to
help.

the `&rest cs` can be omitted and the macro can expand that `clauses` to the result of `ensime-sbt-module-prompt-clauses` and can still keep the manual clause definitions as they currently are.

Clauses is an associative list of lists looking like

> ((?a "[a]pi" "api") ... )

`cases` is another list of lists looking like

> ((?a "api") (?r "root") ... )

They are the cases for the `pcase` macro.  Everything is there as far
as information, but the `cases` are defined as `&rest cases` in the
`pcase` macro and I can't `splice` it because it isn't evaluated, only
expanded.

Trying to get around that, but so far no luck.

**Comment by fommil** [comment]
What version of Emacs are you using?

**Comment by jacobono** [comment]
`24.5.1`

**Comment by fommil** [comment]
@aemoncannon is our elisp guru
