### ISSUE TITLE
Please consider reverting deferral to ensime.org

### ISSUE THREAD

**Issue by mriehl** [ensime/ensime-emacs#345]
Hi,

I'm a scala developer and newcomer to emacs. The `Readme` points me to `ensime.org` where the ["getting started"](http://ensime.github.io/getting_started/) section yells TODO at me.
Honestly this is very off-putting. Please consider reverting recent changes to the `Readme`.

Currently I'm using the git history of the `Readme` file in order to understand how to use ensime...
Personally when I migrate documentation I always do a soft migration - better have a time frame where docs are duplicated than a time frame where there a no docs at all...

**Comment by fommil** [comment]
Why not help us write the docs then?

**Comment by fommil** [comment]
Exactly which "Getting Started" page would we migrate? The reason it says TODO is because nobody has written it yet. Probably you mean the Emacs insertion guide, but that is not the case for the vast majority of newcomers, who want to use atom (at the last three hack days, the combined numbers of vim/sublime/atom totally dwarves Emacs)

ENSIME is a constantly evolving community effort and contributing / using it go hand in hand. All our strategic effort as the core team goes into enabling and making it easier for people to contribute. Hence focus on cleaner code, CI, continuous release, reviews and - now - documentation.

If you would like to get involved in the documentation effort, or get started, I recommend that you join the gitter chat room and we can put you in touch with the people leading this effort and what the goals are.

We will absolutely 100% not be turning back on the move to ensime.org. There is substantial proof that documentation on each repo is impossible to maintain and extremely confusing.

**Comment by fommil** [comment]
FYI I wrote a stub at http://ensime.github.io/getting_started/

**Comment by mriehl** [comment]
Hi,


thanks for your clarification and work! It turns out I was looking for the emacs editor page which describes how to get started with using ensime but somehow missed the content there because it starts with hyperlinks to emacs tutorials.

I will be contributing documentation and/or code for sure. Thanks again!
