### ISSUE TITLE
company not offering yasnippet completions when ensime is enabled

### ISSUE THREAD

**Issue by douglarek** [ensime/ensime-emacs#474]
The document (http://ensime.github.io/editors/emacs/hacks/#completions) did not work well.

```
 class Calculator(brand: String) {
   val color: String = if (brand == "TI") {
     "blue"
   } else if (brand == "HP") {
     "black"
   } else {
     "white"
   }

   def add(m: Int, n: Int) = m + n

   def // type TAB here 
!}
```

```
No completion found
```

But when I type 'M-x yas-expand`, it showed:

```
 def name(args): Unit = {

   }
```

And my emacs config:

```
;; ENhanced Scala Interaction Mode for Emacs
 (require 'ensime)
 (use-package company
   :diminish company-mode
   :commands company-mode
   :init
   (setq
    company-dabbrev-ignore-case nil
    company-dabbrev-code-ignore-case nil
    company-dabbrev-downcase nil
    company-idle-delay 0
    company-minimum-prefix-length 4)
   :config
   ;; disables TAB in company-mode, freeing it for yasnippet
   (define-key company-active-map [tab] nil))

 (add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
```

**Comment by fommil** [comment]
This isn't an ensime thing, it's a company mode thing. I think it only works if you use company to complete a template, or perhaps if there is no space after def. Please update the docs if you solve it.

**Comment by fommil** [comment]
Also you might need to investigate using different ways of saying tab. It's apparently different for terminal vs xwindows.

**Comment by douglarek** [comment]
@fommil thanks for your reply, I tried it using terminal and xwindows, neither of them works. There is no space after def.

**Comment by fommil** [comment]
hmm, I just tried it with ensime mode turned off: I type `defTAB` and then one of the dropdown options is the yassnippet that I can select (arrow keys) and expand (with return).

Then I turned on ensime and it didn't work anymore.

This is starting to look like a bug afterall, but you can ignore the docs above because a lot of this was brought into `ensime-company-enable`.

Do you think you could investigate further?

**Comment by fommil** [comment]
I think I might know what the problem is and there are a few ways to solve it.

For company-mode to offer suggestions based on the yas templates, the ensime completer must return no completions. But since def is a keyword, ensime server returns it as an option.

1. we could not return keywords as completions from the server. This was my preference in the beginning but others pointed out that it avoids duplication in the clients. And besides, this would only solve this `def` completion, not the general problem.
2. we could add `(ensime-company company-yasnippet)` to the head of `company-backends` to ensure that yasnippets are always offered even if ensime has an option. But this will introduce a further problem that if yasnippet has a completion, other company backends will never be used (e.g. keywords and dabbrev). 
3. make our `ensime-company-complete-or-indent` even more sophisticated and fallback to indent only if there is only whitespace from the start of the line to the point or there is no yasnippet completion at point.

My preference would be 3, but as an immediate workaround you can try 2.

```
(push '(ensime-company company-yasnippet) company-backends)
```

**Comment by fommil** [comment]
@douglarek would you like to pick this one up and send a PR?

**Comment by douglarek** [comment]
@fommil thanks for the tips, I am sorry I can't send a PR since I am not very familiar with elisp yet.

**Comment by fommil** [comment]
@douglarek we have excellent resources to learn on our contributing page http://ensime.github.io/editors/emacs/contributing/

**Comment by douglarek** [comment]
@fommil Ok, I will have a look; thanks

**Comment by Kai-Chen** [comment]
From the yasnippet FAQ, here's one of the workarounds

```elisp
(defun yas-advise-indent-function (function-symbol)
  (eval `(defadvice ,function-symbol (around yas-try-expand-first activate)
           ,(format
             "Try to expand a snippet before point, then call `%s' as usual"
             function-symbol)
           (let ((yas-fallback-behavior nil))
             (unless (and (interactive-p)
                          (yas-expand))
               ad-do-it)))))
(yas-advise-indent-function 'ensime-company-complete-or-indent)
```

From an architectural point of view, I like it better to keep the ensime-company-* functions simple and have yasnippet users (including myself) to configure yas to know about the ensime hook, rather than the other way around.  So I think for this issue, it might be sufficient to add the above configuration to the documentation.

**Comment by fommil** [comment]
Yeah this is a difficult one. I personally don't don't use the default setting.

**Comment by zakkak** [comment]
Hey there, if I understand correctly another approach could be the following:

```
(push '(ensime-company :with company-yasnippet) company-backends)
```

**Comment by yangwen0228** [comment]
You can try this, I use it daily. And works perfectly. If ensime is on, use ensime and yasnippet. Otherwise, use dabbrev and yasnippet. Also company-files is used. And I don't think we need any others.
```
(defun unimacs-company-define-backends (modes-backends-cons)
    (let ((modes    (car modes-backends-cons))
          (backends (cdr modes-backends-cons)))
      (dolist (mode modes)
        (let* ((modename (symbol-name mode))
               (funcname (concat "company-backends-for-" modename))
               (func (intern funcname))
               (hook (intern (concat modename "-hook"))))
          (setf (symbol-function func)
                `(lambda ()
                   (set (make-local-variable 'company-backends)
                        ',backends)))
          (add-hook hook func)))))
  ;; company: If ensime is on, use ensime and yasnippet. Otherwise, use dabbrev and yasnippet.
  (unimacs-company-define-backends
   '((ensime-mode) . ((ensime-company :with company-yasnippet)
                      (company-dabbrev-code :with company-dabbrev company-yasnippet)
                      company-files)))
```

**Comment by fommil** [comment]
interesting. I have something much simpler in my config, probably not as good.

**Comment by yangwen0228** [comment]
I write this function to config `company-backends` as a local variable for each major-mode, like:
```
(unimacs-company-define-backends
   '((c-mode c++-mode objc-mode) . ((company-irony :with company-yasnippet)
                                    (company-dabbrev-code :with company-dabbrev company-yasnippet)
                                    company-c-headers company-files)))
```
It seems that it's easier to manage the `company-backens` for each different mode.
