### ISSUE TITLE
formatting doesn't work for test directories

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#539]
@yyadavalli i tried formatting a test file and it ran `myproject/ensimeScalariformOnly` which collapses to `myproject/compile:ensimeScalariformOnly`.

Discovering the phase (compile/test/it/etc) is difficult right now, perhaps we should update the sbt plugin to have the task on the `Project` instead of the config?

**Comment by yyadavalli** [comment]
I am able to get it working by calling it explicitly in `test`scope 
```
a/test:ensimeScalariformOnly a/src/test/scala/FormatMe.scala
```
I'll try to figure out why it doesn't do that automatically.

**Comment by fommil** [comment]
I can see why it doesn't work... the question is if we want to workaround it in emacs or sbt-ensime :-/

**Comment by yyadavalli** [comment]
I'd say we a put a workaround in sbt-ensime, so that other clients don't have to put in similar hacks

**Comment by fommil** [comment]
:+1:

**Comment by yyadavalli** [comment]
`a/ensimeScalariformOnly` is falling back to `a/compile:ensimeScalariformOnly` so can only look through compile directories.

To be able to format test files `a/test:ensimeScalariformOnly` has to be used.

I don't know what you mean by have the task on the project instead of the config, can you please explain. I thought adding it to `projectSettings` adds it to all projects enabling the plugin.

**Comment by fommil** [comment]
`a/compile:task` means on the `compile` config. `a/task` would mean on the project. perhaps it is best to fix/hack this on the emacs side. we will eventually get better support for `config` detection.

**Comment by yyadavalli** [comment]
Yeah, we need a way to figure out if the given buffer belongs to test files.

On a side note, did `ensimeCompileOnly` support compiling test files without prefixing the config before I refactored it

**Comment by fommil** [comment]
don't think so
